services:
  plandex-postgres:
    image: postgres:16
    restart: always
    container_name: plandex-postgres
    environment:
      POSTGRES_PASSWORD: plandex
      POSTGRES_USER: plandex
      POSTGRES_DB: plandex
    volumes:
      - plandex-db:/var/lib/postgresql/data
    # prevent port  dokploy-postgres
    networks:
      - plandex-network

  plandex-server:
    image: plandexai/plandex-server:latest
    # build:
    #   context: .
    #   dockerfile: server/Dockerfile
    volumes:
      - plandex-files:/plandex-server
    ports:
      - "8099:8099"
      - "4000:4000"
    environment:
      DATABASE_URL: "postgres://plandex:plandex@plandex-postgres:5432/plandex?sslmode=disable"
      GOENV: development
      LOCAL_MODE: 1
      PLANDEX_BASE_DIR: /plandex-server
      OLLAMA_BASE_URL: http://llama-server:8080
      
    networks:
      - plandex-network
      - dokploy-network
    depends_on:
      - plandex-postgres
    command: [ "/bin/sh", "-c", "/scripts/wait-for-it.sh plandex-postgres:5432 -- ./plandex-server" ]

volumes:
  plandex-db:
  plandex-files:

networks:
  plandex-network:
  dokploy-network:
    external: true
